### ISSUE TITLE
Correlate comparison table with this proposed ‘awesome’ list of github alternatives

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#13]
https://github.com/ianchanning/awesome-github-alternatives by @ianchanning

**Comment by bderiso** [comment]
Some good and thorough work has been done by @ianchanning

**Comment by ianchanning** [comment]
Thanks! In theory I need to only include 'awesome' alternatives, I'll definitely include GitCenter from the table, but I'm not sure if SIT really meets the criteria.

**Comment by ianchanning** [comment]
There's also issues with GitCenter - there's no publicly available information for it, not even something like a license so there's not much I can write about it, other that it's written in JavaScript

**Comment by ianchanning** [comment]
I think your table could do with an extra row of 'learning required to install', The Zero Net is very interesting, but learning about it is levels of difficulty above any of the other options, not that that's a bad thing. However one of the major selling points of GitHub was that it made contributing to open source projects as easy as joining a forum. The other self hosted options are obviously more complex than GitHub, but they're at a level of installing your own blog, which is a reasonable alternative.
