### ISSUE TITLE
Github's Motives

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#2]
As user luke-jr notes: [GitHub was already centralized & non-free before the acquisition](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/1#issuecomment-394301394).

Therefore most concerns about Microsoft were already a problem and they're just being amplified and brought to the forefront.

Github was already closed-source & profit-motivated. While it was adopted by many FOSS projects, Github was not necessarily the bastion of openness that it's reputation & userbase implies.

# Counterpoint
Being closed-source & publicly traded neither guarantees nor prevents a company from fostering a healthy community. Indeed,[ the heart of open-source is that you can be both open **and** profitable.](https://www.gnu.org/philosophy/selling.html)

[Microsoft's financial independence _could_ even offer GitHub the freedom to consider open-sourcing their code without any financial concerns (real or imagined).](https://github.com/dear-github/dear-github/issues/304)

In the end, if the open-source community isn't satisfied with the actions of the new management, then they can & will leave. I don't know of any legal precedence that previously uploaded code (if properly licensed) could be lost to the owners.

**Comment by tycho01** [comment]
![one MILLION dollars](https://media.giphy.com/media/sEULHciNa7tUQ/giphy.gif)
