### ISSUE TITLE
Compile a list or core features that we want from a replacement

### ISSUE THREAD

**Issue by bderiso** [bderiso/Microsoft-Github-acquisition#5]
These can be core features or nice-to-have wishes.

* [Git repo hosting](https://github.com/features#code-hosting)
  * Public
  * Private
* [Pull Requests / Code Review](https://github.com/features#code-review)
* [Issue Tracking / Project Management](https://github.com/features#project-management)
* [Collaboration / Team Management](https://github.com/features#team-management)
* [Community / Social Network](https://github.com/features#social-coding)
* [Documentation](https://github.com/features#documentation)
* Open-Source
* Decentralized ownership & management
* Extensibility API

**Comment by marcus-sa** [comment]
I actually think we should just include all the features from https://github.com/features and more to.
Maybe not the project management feature is that relevant, instead we could somewhere in the near future make an API, so project management tools like https://wrike.com can access it instead.

**Comment by bderiso** [comment]
Committing the list here for pushing to other interested repos.

https://github.com/bderiso/Microsoft-Github-acquisition/blob/master/Features.md

**Comment by bderiso** [comment]
For any more additions, just make a commit or PR against that file ^
