### ISSUE TITLE
On the differences, pros and cons of the alternatives

### ISSUE THREAD

**Issue by Serphentas** [bderiso/Microsoft-Github-acquisition#7]
There are many alternatives listed [here](https://github.com/bderiso/Microsoft-Github-acquisition/blob/master/Github%20Alternatives.md), but an in-depth comparison is needed in order to properly determine which one(s) fulfil the [needed features](https://github.com/bderiso/Microsoft-Github-acquisition/blob/master/Features.md) best.

I've went ahead and created a [spreadsheet](https://docs.google.com/spreadsheets/d/1LZryaOx4VYHQ_oWLtRjvFrr4RhVjR484eFe7du3Usa4/edit?usp=sharing) in which people shall list the differences and the pros & cons of each, with respect to the community's needs (i.e. this is not a place to say X is better than Y just to say that Y sucks).

Feel free to comment on the document or here if you have any questions regarding the way of doing this comparison.

**Comment by bderiso** [comment]
Thanks for making this; I'll work to incorporate this into the list as we go

**Comment by Serphentas** [comment]
No problem

**Comment by bderiso** [comment]
I'll chip-in there as well if you grant me permissions 👍

**Comment by Serphentas** [comment]
Done

**Comment by bderiso** [comment]
[New wiki](https://github.com/bderiso/Microsoft-Github-acquisition/wiki/GitHub-Alternatives)

**Comment by Serphentas** [comment]
How do you put new content in the Wiki ? Update the page manually or do an export of some sort ?

**Comment by Serphentas** [comment]
Also, how to bring notes on cells in there ? I guess a list of "A2: blah" would do the job.

**Comment by Apollia** [comment]
Someone's [comment on another issue](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/81#issuecomment-395194072) pointed out this useful link:

https://git.wiki.kernel.org/index.php/GitHosting

**Comment by Serphentas** [comment]
Thanks, I'll put that as a resource (and also use it to complete the document).

**Comment by bderiso** [comment]
@Serphentas re: Wiki
You edit the page manually; you're given a chance to make a "commit message" when you save changes and there is a revision history where you can compare & then revert changes

**Comment by bderiso** [comment]
@Serphentas re: notes into wiki, I think emb edding the page might accomplish that, or perhaps there's a convenient way to export them?

**Comment by Serphentas** [comment]
@bderiso We can export to PDF like so: [GitHub alternatives - comparison - Sheet1.pdf](https://github.com/bderiso/Microsoft-Github-acquisition/files/2085014/GitHub.alternatives.-.comparison.-.Sheet1.pdf)

There's also ODS which we can easily edit. I think exporting to both formats is the way to go, so that we can easily view on the go (PDF) and easily edit the document (ODS).

What do you think ?

**Comment by bderiso** [comment]
I really like working with markdown tables, but it started to get a bit unwieldy with the amount of info, so I assumed nobody else would want to mess with it.

I think the system you've set-up works well for now.

**Comment by Serphentas** [comment]
> I think the system you've set-up works well for now.

That means the PDF+ODS export ?

**Comment by bderiso** [comment]
Yes
