### ISSUE TITLE
Keep "Editorializing" to a Minimum

### ISSUE THREAD

**Issue by Omeryl** [bderiso/Microsoft-Github-acquisition#8]
It hasn't happened yet, and I'm sure it won't, but logging the issue none-the-less is appropriate.

Let's not needlessly edit other's issues, or delete them, to cause unnecessary friction on this topic.

**Comment by bderiso** [comment]
Agreed 100%. The sort of attitude you’re referencing is the exact reason I created this repo instead of participating elsewhere.

**Comment by bderiso** [comment]
https://github.com/bderiso/Microsoft-Github-acquisition/pull/9#issue-193065957

I've added this concern as the top example of unacceptable behavior in our new [Code Of Conduct](https://github.com/bderiso/Microsoft-Github-acquisition/blob/master/CODE_OF_CONDUCT.md).

Please feel free to request any additions as a Pull Request against that file, and thanks for raising this issue!
